# Generated by Django 4.2.2 on 2023-07-11 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_room_message_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 18, 16, 7, 136879, tzinfo=datetime.timezone.utc)),
        ),
    ]
